name: flashing_widget
description: A customizable Flutter widget that creates a flashing animation effect before executing a callback function.
version: 1.0.0
homepage: https://github.com/tjbaba/flashing_widget
repository: https://github.com/tjbaba/flashing_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# This package does not contain any assets